### ISSUE TITLE
Cmake and Make generate incomplete builds

### ISSUE THREAD

**Issue by kamescg** [barryWhiteHat/miximus#36]
First, thanks publishing this project! Can't wait to see a product ready trustless Ethereum mixer.

I'm running into some difficulties during the make process.

Because I'm running OSX I'm including additional parameters during the `cmake ... && make` steps borrowed from the snark-mixer repo. I'm not sure if this is causing issues during the make process, but for whatever reason the `/build/src/libmiximus.so` file which is required in the test.py/deploy.py files isn't being generated

```
LD_LIBRARY_PATH=/usr/local/opt/openssl/lib:"${LD_LIBRARY_PATH}"                    
CPATH=/usr/local/opt/openssl/include:"${CPATH}"                                    
PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:"${PKG_CONFIG_PATH}"          
export LD_LIBRARY_PATH CPATH PKG_CONFIG_PATH       

CPPFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig cmake -DWITH_PROCPS=OFF -DWITH_SUPERCOP=OFF ..
``` 

The following is the output generated when I attempt to run `python3 test.py`

```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    from deploy import *
  File "../snarkWrapper/deploy.py", line 38, in <module>
    lib = cdll.LoadLibrary('../build/src/libmiximus.so')
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(../build/src/libmiximus.so, 6): image not found
```

Any thoughts as to why this might be occurring?

**Comment by barryWhiteHat** [comment]
can you show me the output of the cmake/make error?

**Comment by barryWhiteHat** [comment]
Also have you looked at  https://github.com/HarryR/ethsnarks-miximus ?

Its a much clearner implmentation of what i have here.
